#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.dirname(__FILE__))

require 'thor'
require 'lib/url/list_products_from_json'
require 'lib/url/list_products_from_xml'
require 'lib/logs/list_highest_traffic_hostnames'
require 'lib/logs/list_most_requested_files'

class LaserLocust < Thor
  desc 'list_highest_traffic_hostnames LOG_FILE_PATH', 'list hostnames with highest traffic'
  def list_highest_traffic_hostnames(log_file_path)
    Logs::ListHighestTrafficHostnames.list(log_file_path)
  end

  desc 'list_most_requested_files LOG_FILE_PATH', 'list mosts requested files'
  def list_most_requested_files(log_file_path)
    Logs::ListMostRequestedFiles.list(log_file_path)
  end

  desc 'list_products_from_url URL', 'Parse and list products from XML Feed'
  def list_products_from_xml(url)
    Url::ListProductsFromXml.new(url).list
  end

  desc 'list_products_from_json URL', 'Parse and list products from JSON Feed'
  def list_products_from_json(url)
    Url::ListProductsFromJson.new(url).list
  end
end

LaserLocust.start(ARGV)
